@startuml
entity sponsors {
    id: int
    sponsor_name: string
    description: string
}

entity contacts {
    id: int
    fname: string
    lname: string
    role: string
    email: string
    phone: string
    --
    sponsor_id: int <<FK>>
}

entity club_reps {
    id: int
    fname: string
    lname: string
    email: string
    phone: string
}

entity contributions {
    id: int
    donation: string
    description: string
    monetary_value: float
    temporal_value: string
    date: date
    --
    sponsor_id: int <<FK>>
    contact_id: int <<FK>>
    club_rep_id: int <<FK>>
    club_dept_id: int <<FK>>
    type_id: int <<FK>>
    project_id: int <<FK>>
}

enum contribution_types <<enum>> {
    ENVIRONMENT
    EQUIPEMENT
    MATERIAL
    MONEY
    SERVICE
}

entity follow_ups {
    id: int
    date: date
    description: string
    status: string
    --
    contribution_id: int <<FK>>
}

entity projects {
    id: int
    project_name: string
    description: string
}

enum club_departments <<enum>> {
    ALUMNI
    ELECTRICAL
    GENERAL
    MECHANICAL
    SOFTWARE
}

sponsors ||-r--o{ contacts : "employ"
contacts ||-d-|{ contributions : "coordinated 1 or many \ncontributions"
sponsors ||-d-|{ contributions : "donated 1 or many \ncontributions"
club_reps ||-d-o{ contributions : "obtained 0 or many \ncontributions"

projects ||-r-o{ contributions : "benefited from 0 or many \ncontributions"
club_departments }o-l-o{ contributions : "0 or many contributions \nhelped 0 or many club departments"

contributions ||-d-|| contribution_types : "are of type"
contributions ||-d-o{ follow_ups : "require 0 or many \nfollow up(s)"

note right of follow_ups::status
    - pending
    - in progress
    - completed
    - cancelled
    - closed
end note

@enduml